[package]
edition = '2021'
name = 'sold'
version = '0.73.0'

[[bin]]
name = 'sold'
path = 'src/main.rs'

[dependencies]
anyhow = "1.0.81"
atty = '0.2'
dunce = '1.0'
failure = '0.1'
once_cell = '1.18'
serde_json = { features = [ 'unbounded_depth' ], version = '1.0' }
strip-ansi-escapes = '0.2'
clap = { features = [ 'derive' ], version = '4.3' }
serde = { features = [ 'derive' ], version = '1.0' }
tvm_abi = { git = 'https://github.com/tvmlabs/tvm-sdk.git', tag = 'rc-1.47.0' }
tvm_assembler = { git = 'https://github.com/tvmlabs/tvm-sdk.git', tag = 'rc-1.47.0' }
tvm_block = { git = 'https://github.com/tvmlabs/tvm-sdk.git', tag = 'rc-1.47.0' }
tvm_types = { git = 'https://github.com/tvmlabs/tvm-sdk.git', tag = 'rc-1.47.0' }

[build-dependencies]
cmake = '0.1'

[dev-dependencies]
assert_cmd = '2.0'
predicates = '3.0'

[lib]
name = 'sold_lib'
path = 'src/lib.rs'
